[{'class_period': (1, 2),
  'location': '大学城校区 A1102',
  'name': '信息经济学',
  'professor': '张馨之',
  'student_number': '40',
  'week_day': 1,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (1, 2),
  'location': '大学城校区 A1304',
  'name': '金融工程',
  'professor': '范闽',
  'student_number': '58',
  'week_day': 2,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (1, 2),
  'location': '大学城校区 A2105',
  'name': '商业银行经营管理',
  'professor': '钟永红',
  'student_number': '31',
  'week_day': 3,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (1, 2),
  'location': '大学城校区 A1102',
  'name': '信息经济学',
  'professor': '张馨之',
  'student_number': '40',
  'week_day': 3,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (1, 2),
  'location': '大学城校区 A1304',
  'name': '金融工程',
  'professor': '范闽',
  'student_number': '58',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A1407',
  'name': '国际金融',
  'professor': '陈平',
  'student_number': '30',
  'week_day': 1,
  'week_period': (1, 13),
  'week_period_text': '1-13周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A1306',
  'name': '运筹学',
  'professor': '李成安',
  'student_number': '1',
  'week_day': 2,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A1504',
  'name': '时间序列分析--基于R',
  'professor': '贺建风',
  'student_number': '29',
  'week_day': 2,
  'week_period': (1, 16),
  'week_period_text': '1-16周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A1105',
  'name': '智能优化算法及其应用',
  'professor': '黄晓宇',
  'student_number': '30',
  'week_day': 3,
  'week_period': (1, 16),
  'week_period_text': '1-16周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A2203',
  'name': '保险学原理',
  'professor': '茹璟',
  'student_number': '128',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A2204',
  'name': '金融经济学',
  'professor': '杨科',
  'student_number': '12',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A1306',
  'name': '运筹学',
  'professor': '李成安',
  'student_number': '1',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A2403',
  'name': '智能优化算法及其应用',
  'professor': '黄晓宇',
  'student_number': '30',
  'week_day': 5,
  'week_period': (1, 16),
  'week_period_text': '1-16周'},
 {'class_period': (5, 6),
  'exclude_week': [6],
  'location': '大学城校区 A1407',
  'name': '国际金融',
  'professor': '陈平',
  'student_number': '30',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-5周,7-12周'},
 {'class_period': (5, 6),
  'location': '大学城校区 A2105',
  'name': '商业银行经营管理',
  'professor': '钟永红',
  'student_number': '31',
  'week_day': 5,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (7, 8),
  'location': '大学城校区 A2203',
  'name': '保险学原理',
  'professor': '茹璟',
  'student_number': '128',
  'week_day': 1,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (7, 8),
  'location': '大学城校区 A2204',
  'name': '金融经济学',
  'professor': '杨科',
  'student_number': '12',
  'week_day': 1,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (7, 8),
  'exclude_week': [7, 10, 11],
  'location': '大学城校区 A2207',
  'name': '金融市场学',
  'professor': '齐昌玮',
  'student_number': '87',
  'week_day': 4,
  'week_period': (1, 15),
  'week_period_text': '1-6周,8-9周,12-15周'},
 {'class_period': (7, 8),
  'exclude_week': [10, 11],
  'location': '大学城校区 A2207',
  'name': '金融市场学',
  'professor': '齐昌玮',
  'student_number': '87',
  'week_day': 5,
  'week_period': (1, 14),
  'week_period_text': '1-9周,12-14周'},
 datetime.date(2019, 2, 25)]