[{'class_period': (1, 2),
  'location': '大学城A1101',
  'name': '国际金融',
  'professor': 'Joe Kong',
  'week_day': 1,
  'week_period': (15, 15),
  'week_period_text': '15周'},
 {'class_period': (1, 2),
  'location': '大学城A1102',
  'name': '商业银行经营管理',
  'professor': '钟永红',
  'week_day': 3,
  'week_period': (15, 15),
  'week_period_text': '15周'},
 {'class_period': (1, 2),
  'location': '大学城A1303',
  'name': '金融工程',
  'professor': '范闽',
  'week_day': 3,
  'week_period': (16, 16),
  'week_period_text': '16周'},
 {'class_period': (1, 2),
  'location': '大学城A2203',
  'name': '金融市场学',
  'professor': '齐昌玮',
  'week_day': 4,
  'week_period': (16, 16),
  'week_period_text': '16周'},
 {'class_period': (1, 2),
  'location': '大学城A1102',
  'name': '智能优化算法及其应用',
  'professor': '黄晓宇',
  'week_day': 3,
  'week_period': (18, 18),
  'week_period_text': '18周'},
 {'class_period': (1, 2),
  'location': '大学城A1103',
  'name': '时间序列分析--基于R',
  'professor': '贺建风',
  'week_day': 2,
  'week_period': (19, 19),
  'week_period_text': '19周'},
 datetime.date(2019, 2, 25)]
