[{'class_period': (7, 8),
  'location': '大学城校区 A2203',
  'name': '保险学原理',
  'professor': '茹璟',
  'student_number': '130',
  'week_day': 1,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A2203',
  'name': '保险学原理',
  'professor': '茹璟',
  'student_number': '130',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
  datetime.date(2019, 2, 25)]
