[{'class_period': (1, 2),
  'location': '大学城校区 A1102',
  'name': '信息经济学',
  'professor': '张馨之',
  'student_number': '42',
  'week_day': 1,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (1, 2),
  'location': '大学城校区 A1102',
  'name': '信息经济学',
  'professor': '张馨之',
  'student_number': '42',
  'week_day': 3,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
  datetime.date(2019, 2, 25)]
