[{'class_period': (7, 8),
  'location': '大学城校区 A2204',
  'name': '金融经济学',
  'professor': '杨科',
  'student_number': '14',
  'week_day': 1,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 {'class_period': (3, 4),
  'location': '大学城校区 A2204',
  'name': '金融经济学',
  'professor': '杨科',
  'student_number': '14',
  'week_day': 4,
  'week_period': (1, 12),
  'week_period_text': '1-12周'},
 datetime.date(2019, 2, 25)]
